#!/bin/sh
# GENERATED by skill-packs.sh --compile from registry.tsv and every pack's
# policy.tsv + policy.local.tsv. Do not hand-edit: run
# sh .claude/scripts/skill-packs.sh --compile again instead. Sourced by
# mcp-guard.sh, which fails open if this file is missing or broken.
#
# Both functions below spawn exactly one awk process per call, and read
# nothing off disk: the rule tables are the shell variables right here,
# written fresh by every --compile run.

LH_PACK_DETECT_RULES='ghl	GoHighLevel	^(execute_operation|list_locations|search_operations|describe_operation|locations_get-location|socialmediaposting_.*|social-media-posting_.*|conversations_.*|contacts_get-contacts)$
apollo	Apollo	^apollo_
gmail	Gmail	^(create_draft|list_drafts|search_threads|get_thread|list_labels|label_thread|update_draft|get_draft)$
outlook	Microsoft 365 (Outlook)	^outlook_'

LH_PACK_DENY_RULES='^apollo_domain_purchase_index$	Launchhouse never spends the founder'"'"'s money from here, including browsing what Apollo would sell them. If they want a domain, they buy it themselves in Apollo.
^apollo_email_account_purchase_index$	Launchhouse never spends the founder'"'"'s money from here, including browsing mailboxes Apollo would sell them. If they want a mailbox, they buy it themselves in Apollo.
^apollo_email_account_purchase_create$	Launchhouse never buys anything on the founder'"'"'s account. If they want a mailbox, they buy it in Apollo themselves.
^apollo_agent_manage_billing$	Launchhouse never spends the founder'"'"'s money or changes their plan from here. If they want to change plans, seats or credits, they do it themselves in Apollo'"'"'s own billing settings.
^apollo_agent_workflow_automation$	Launchhouse builds sequences and automations paused, for the founder to switch on themselves in Apollo having read them. An agent tool that sets up its own automation could enrol, message or start something without that reading ever happening.
^apollo_website_visitor_domain_tracker_send_install_email$	This emails a real person, such as the founder'"'"'s own developer, on Apollo'"'"'s behalf. Launchhouse never sends email from a tool; show the founder the install script and let them send it themselves.
^outlook_send_mail$	Launchhouse never sends from the founder'"'"'s mailbox. Claude writes drafts only, and the founder presses Send themselves.
^outlook_forward_mail$	Launchhouse never forwards from the founder'"'"'s mailbox. If the founder wants something forwarded, they do it from their own Outlook.
^outlook_send_draft$	Launchhouse never sends from the founder'"'"'s mailbox. A drafted reply gets the founder'"'"'s own Send, in their own Outlook, never this tool.
^outlook_batch_delete_messages$	Launchhouse never deletes a founder'"'"'s mail in bulk from here. If they want messages gone, they delete them themselves in Outlook.
^outlook_batch_modify_labels$	Launchhouse never relabels a founder'"'"'s mail in bulk from here. If they want this, they do it themselves in Outlook.
^outlook_set_vacation$	Launchhouse never sets an auto-reply on the founder'"'"'s mailbox; it would answer real people without them seeing each reply. If they want one, they set it themselves in Outlook.
^outlook_create_filter$	Launchhouse never sets up mail rules, which can forward or file the founder'"'"'s mail without them seeing it. If they want one, they make it in their mail app themselves.
^close_session$	This unofficial LinkedIn connector is never used to manage a LinkedIn session at all, closing it included. LinkedIn'"'"'s own User Agreement bars unauthorized automated access (../../references/social-accounts.md); the founder manages their own LinkedIn session by signing in and out themselves.
^connect_with_person$	Launchhouse never sends a LinkedIn connection request from here. LinkedIn'"'"'s own User Agreement bars bots or automated methods that add contacts; the founder sends every connection request by hand, from LinkedIn itself.
^send_message$	Launchhouse never sends a LinkedIn message from here, cold or otherwise. LinkedIn'"'"'s own User Agreement bars automated sends; the founder sends every message by hand, from LinkedIn itself.'

LH_PACK_ASK_RULES='^apollo_agent_find_prospects$	This agent tool can return enriched prospect data. Apollo'"'"'s own enrichment and bulk enrichment calls spend credits, and this tool is not documented as free, so treat it like apollo_people_match: check the founder has seen an estimated cost and said yes before it runs.
^apollo_contacts_bulk_create$	This creates many real people'"'"'s contact records in the founder'"'"'s Apollo account in one call. Check the founder has seen who they are, such as the list of 25, and said yes first.
^apollo_accounts_bulk_create$	This creates many real companies'"'"' account records in the founder'"'"'s Apollo account in one call. Check the founder has said yes to the list first.
^delete_draft$	Deleting a draft is permanent, not a move to Trash. Check the founder actually wants that draft gone before it disappears.
^delete_label$	Deleting a label removes it from every message that carries it. Check the founder named this label before it goes.
^trash_message$	Trashing a prospect'"'"'s message or the founder'"'"'s own sent mail could hide it from the next reply search. Check first.
^trash_thread$	Same as trash_message, for a whole thread.
^mark_message_spam$	Marking a message as spam can hide a genuine reply from ever being found by search. Check first.
^mark_thread_spam$	Same as mark_message_spam, for a whole thread.
^update_label$	Renaming or recoloring a label changes it everywhere it is used in the founder'"'"'s mailbox. Check first.
^create_label$	A new label changes the founder'"'"'s own organizing system. Check they actually want one before adding it.
^outlook_trash_thread$	Launchhouse: this moves a founder'"'"'s mail to Trash. Show them what it will remove and check they said yes.
^outlook_delete_draft$	Launchhouse: this deletes a drafted email before the founder has sent it. Check they said yes before it goes.
^outlook_delete_label$	Launchhouse: this deletes a category the founder may still use to find mail. Check they said yes before it goes.
^outlook_delete_filter$	Launchhouse: this deletes a mail rule from the founder'"'"'s own mailbox. Check they said yes before it goes.
^outlook_create_event$	Launchhouse: this changes the founder'"'"'s calendar. Show them what it will do and check they said yes.
^outlook_update_event$	Launchhouse: this changes the founder'"'"'s calendar. Show them what it will do and check they said yes.
^outlook_respond_to_event$	Launchhouse: this answers a calendar invite for the founder. Show them what it will do and check they said yes.
^get_company_employees$	This unofficial LinkedIn connector risks the founder'"'"'s account being restricted or banned, a decision LinkedIn does not reverse on request (../../references/social-accounts.md). Check the founder actually wants this read before it runs, and offer the export route instead: their own LinkedIn "Get a copy of your data" archive, added with /growth-engine:add-files.
^get_company_posts$	Same ban risk as every other call on this unofficial connector. Check the founder wants this read, and offer the export route instead: /growth-engine:add-files with their own LinkedIn data.
^get_company_profile$	Same ban risk as every other call on this unofficial connector. Check the founder wants this read, and offer the export route instead: /growth-engine:add-files with their own LinkedIn data.
^get_conversation$	Same ban risk as every other call on this unofficial connector. Check the founder wants this read, and offer the export route instead: /growth-engine:add-files with their own LinkedIn data.
^get_feed$	Same ban risk as every other call on this unofficial connector. Check the founder wants this read, and offer the export route instead: /growth-engine:add-files with their own LinkedIn data.
^get_inbox$	Same ban risk as every other call on this unofficial connector. Check the founder wants this read, and offer the export route instead: /growth-engine:add-files with their own LinkedIn data.
^get_job_details$	Same ban risk as every other call on this unofficial connector. Check the founder wants this read, and offer the export route instead: /growth-engine:add-files with their own LinkedIn data.
^get_my_profile$	Same ban risk as every other call on this unofficial connector, even for the founder'"'"'s own profile. Check the founder wants this read, and offer the export route instead: their own "Save to PDF" or "Get a copy of your data" from LinkedIn itself, added with /growth-engine:add-files.
^get_person_profile$	Same ban risk as every other call on this unofficial connector. Check the founder wants this read, and offer the export route instead: /growth-engine:add-files with their own LinkedIn data.
^get_sidebar_profiles$	Same ban risk as every other call on this unofficial connector. Check the founder wants this read, and offer the export route instead: /growth-engine:add-files with their own LinkedIn data.
^search_companies$	Same ban risk as every other call on this unofficial connector. Check the founder wants this read, and offer the export route instead: /growth-engine:add-files with their own LinkedIn data.
^search_conversations$	Same ban risk as every other call on this unofficial connector. Check the founder wants this read, and offer the export route instead: /growth-engine:add-files with their own LinkedIn data.
^search_jobs$	Same ban risk as every other call on this unofficial connector. Check the founder wants this read, and offer the export route instead: /growth-engine:add-files with their own LinkedIn data.
^search_people$	Same ban risk as every other call on this unofficial connector, and the shape of read a scraper would use at scale. Check the founder wants this read, and offer the export route instead: /growth-engine:add-files with their own LinkedIn data.
^(cloudflare_)?(dns_record|zone_dns_record|dns)s?_(create|update|edit|patch|write)$	Adding or changing a DNS record can break the founder'"'"'s mail or their site if it is wrong. Check the founder has seen the exact record (type, name, value, TTL) and said yes before it is written.
^(cloudflare_)?(dns_record|zone_dns_record|dns)s?_delete$	Deleting a DNS record can break the founder'"'"'s mail or their site, and is never part of a vague "clean up." Check the founder named this exact record and said yes before it is removed.'

# Which pack a tool suffix belongs to, first match in registry order. Sets
# lh_pack_id and lh_pack_name, both empty when nothing matches.
lh_pack_detect() {
  suffix=$1
  lh_pack_id=""
  lh_pack_name=""
  lh_pd_out=$(printf '%s' "$suffix" | RULES="$LH_PACK_DETECT_RULES" awk -F '\t' '
    BEGIN { n = split(ENVIRON["RULES"], arr, "\n") }
    {
      s = $0
      for (i = 1; i <= n; i++) {
        if (arr[i] == "") continue
        split(arr[i], f, "\t")
        if (f[3] != "" && s ~ f[3]) { print f[1] "\t" f[2]; exit }
      }
    }')
  [ -n "$lh_pd_out" ] || return 0
  lh_pd_tab=$(printf '\t')
  lh_pack_id=${lh_pd_out%%"$lh_pd_tab"*}
  lh_pack_name=${lh_pd_out#*"$lh_pd_tab"}
}

# The strictest pack policy for a tool suffix: deny beats ask. Sets
# lh_pack_decision (deny, ask, or empty) and lh_pack_reason.
lh_pack_policy() {
  suffix=$1
  lh_pack_decision=""
  lh_pack_reason=""
  lh_pp_out=$(printf '%s' "$suffix" | DENY="$LH_PACK_DENY_RULES" ASK="$LH_PACK_ASK_RULES" awk -F '\t' '
    BEGIN {
      dn = split(ENVIRON["DENY"], darr, "\n")
      an = split(ENVIRON["ASK"], aarr, "\n")
    }
    {
      s = $0
      for (i = 1; i <= dn; i++) {
        if (darr[i] == "") continue
        split(darr[i], f, "\t")
        if (f[1] != "" && s ~ f[1]) { print "deny\t" f[2]; exit }
      }
      for (i = 1; i <= an; i++) {
        if (aarr[i] == "") continue
        split(aarr[i], f, "\t")
        if (f[1] != "" && s ~ f[1]) { print "ask\t" f[2]; exit }
      }
    }')
  [ -n "$lh_pp_out" ] || return 0
  lh_pp_tab=$(printf '\t')
  lh_pack_decision=${lh_pp_out%%"$lh_pp_tab"*}
  lh_pack_reason=${lh_pp_out#*"$lh_pp_tab"}
}
